version: '3.7'

services:
  # mssql
  mssql:
    image: microsoft/mssql-server-linux:latest
    container_name: mssql
    networks:
      - mssql
    ports:
      - 1433:1433
    environment:
      - "TZ=${TZ:-Asia/Tokyo}"
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=mssqlPassword!"

networks:
  mssql:
