version: '3.7'

services:
  # mysql
  mysql:
    image: mysql:5.7
    container_name: mysql5.7
    networks:
      - mysql
    ports:
      - 3306:3306
    volumes:
      - ./init.d:/docker-entrypoint-initdb.d
      - ./conf.d:/etc/mysql/conf.d
    environment:
      - "TZ=${TZ:-Asia/Tokyo}"
      - "MYSQL_ROOT_PASSWORD=mysql"
      - "MYSQL_DATABASE=mysql"
      - "MYSQL_USER=mysql"
      - "MYSQL_PASSWORD=mysql"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

networks:
  mysql:
